Adding AES encryption service and unit tests.
IowaComputerGurus/netcore.utilities pull request #7
Opened 2021-11-29 03:25 UTC by kenny-sellers

Closes #4

2021-11-29 03:38 UTC, mitchelsellers requested changes
Overall this looks good, just a few comments on documentation changes and a few cleanup items.

Additionally, we should add information to the Readme.md file to document usage of these options.

Lastly, we might want to consider an additional enhancement for this where the Secret/IV is passed in, we can make a separate PR for this.

**NOTE** This PR changes a public API interface and is a breaking change, this dependency change will impact other libraries.

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities.Tests/AesEncryptionServiceTests.cs
> +        [Theory]
```suggestion
        ///<summary>
        ///    This test is need to ensure that stored values, that were encrypted with the known IV/Secret still can be properly decrypted.  This was necessary after weird behaviors noticed in .NET 5 -> .NET 6 transition
        /// </summary>
        [Theory]
```

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities/AesEncryptionService.cs
> +    ///     Represents a service that can encrypt and decrypt strings using symmetric AES encryption.
```suggestion
    ///     Represents a service that can encrypt and decrypt strings using symmetric AES encryption, using a stored key/iv.
```

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities/AesEncryptionService.cs
> +        ///     Decrypts the provided string into an AES encrypted string.
```suggestion
        ///     Decrypts the provided string from an AES encrypted string back to plain text.
```

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities/AesEncryptionService.cs
> +        ///     Encrypts the provided string into an AES encrypted string.
```suggestion
        ///     Encrypts the provided plain-text string into an AES encrypted string.
```

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities/AesEncryptionService.cs
> +            byte[] encrypted;
This is not needed and should be removed

2021-11-29 03:38 UTC, mitchelsellers commented on src/NetCore.Utilities/DependencyResolution/StartupExtensions.cs
>          /// <param name="services">Your existing services collection</param>
Need to add <param> tag for configuration

2021-11-29 03:45 UTC, mitchelsellers commented on src/NetCore.Utilities/AesEncryptionService.cs
> +            byte[] encrypted;
This is ONLY talking about the `byte[] encrypted;` line

2021-11-29 14:52 UTC, kenny-sellers commented
@mitchelsellers Should be ready for your review

2021-11-30 05:35 UTC, mitchelsellers approved these changes

2021-11-30 05:35 UTC, merged